# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development:
   adapter: mysql
   database: favblog_development
   username: rails
   password: rails
   host: localhost
   socket: /var/run/mysqld/mysqld.sock

test:
   adapter: mysql
   database: favblog_test
   username: rails
   password: rails
   host: localhost
   socket: /var/run/mysqld/mysqld.sock

production:
   adapter: mysql
   database: favblog_production
   username: rails
   password: rails
   host: localhost
   socket: /var/run/mysqld/mysqld.sock
